<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sgr.Domain\Sgr.Domain.csproj" />
    <ProjectReference Include="..\Sgr.Persistence\Sgr.Persistence.csproj" />
    <ProjectReference Include="..\Sgr.Modules.Surveys\Sgr.Modules.Surveys.csproj" />
    <ProjectReference Include="..\Sgr.Modules.Points\Sgr.Modules.Points.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
