using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Sgr.Domain.Audit;
using Sgr.Modules.Surveys.Application;

namespace Sgr.Backend.Api.Controllers;

[ApiController]
[Authorize]
[Route("api/v1/surveys")]
[Produces("application/json")]
public sealed class SurveysController : ControllerBase
{
    private readonly ICreateSurveyService _create;
    private readonly IListSurveysService _list;

    public SurveysController(ICreateSurveyService create, IListSurveysService list)
    {
        _create = create;
        _list = list;
    }

    /// <summary>List surveys visible to the current user.</summary>
    [HttpGet]
    [ProducesResponseType(typeof(IReadOnlyList<SurveyDto>), StatusCodes.Status200OK)]
    public async Task<ActionResult<IReadOnlyList<SurveyDto>>> List(
        [FromQuery] string? status,
        CancellationToken ct)
    {
        var current = CurrentUserAccessor.FromPrincipal(User);
        var result = await _list.ListAsync(current, status, ct);
        return Ok(result);
    }

    /// <summary>Create a new survey. Idempotent by client-generated GUID (RN-06).</summary>
    [HttpPost]
    [ProducesResponseType(typeof(SurveyDto), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    public async Task<ActionResult<SurveyDto>> Create(
        [FromBody] CreateSurveyDto body,
        CancellationToken ct)
    {
        var current = CurrentUserAccessor.FromPrincipal(User);

        var origin = body.Origin ?? AuditOrigin.WebEdit;
        var request = new CreateSurveyRequest(
            SurveyId: body.Id,
            Name: body.Name,
            Description: body.Description,
            TemplateVersionId: body.TemplateVersionId,
            Tags: body.Tags,
            Origin: origin,
            DeviceId: body.DeviceId,
            TimestampOriginal: body.TimestampOriginal ?? DateTime.UtcNow);

        var result = await _create.CreateAsync(request, current, ct);
        return CreatedAtAction(nameof(List), new { }, result);
    }
}

public sealed class CreateSurveyDto
{
    /// <summary>GUID generated by the client (RN-06).</summary>
    [Required]
    public Guid Id { get; set; }

    [Required, MaxLength(200)]
    public string Name { get; set; } = default!;

    [MaxLength(1000)]
    public string? Description { get; set; }

    /// <summary>If null, the root template (latest published version) is used.</summary>
    public Guid? TemplateVersionId { get; set; }

    [MaxLength(500)]
    public string? Tags { get; set; }

    /// <summary>web_edit | mobile_capture | mobile_edit | web_manual_upload</summary>
    [MaxLength(32)]
    public string? Origin { get; set; }

    [MaxLength(64)]
    public string? DeviceId { get; set; }

    public DateTime? TimestampOriginal { get; set; }
}
