<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Sgr.Domain\Sgr.Domain.csproj" />
    <ProjectReference Include="..\Sgr.Persistence\Sgr.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.405" />
    <PackageReference Include="FluentFTP" Version="51.1.0" />
    <PackageReference Include="MetadataExtractor" Version="2.9.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
    <PackageReference Include="SSH.NET" Version="2024.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
